package com.julianne.taskmanager.entities;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data // at compile time generates getters, setters, constructors
@NoArgsConstructor // empty default constructor
@Document(collection = "tasks")
public class Task {

    // mongodb uses ObjectId as the default _id - a globally unique identifier
    @Id
    private String id; // spring data auto-converts ObjectID to String

    @NotBlank
    private String title;
    private String description;
    private Status status = Status.TODO;
    private LocalDateTime dueDate;
    private LocalDateTime createdAt = LocalDateTime.now();

    // constructor without id (autogenerated)
    public Task(String title,
                String description,
                Status status,
                LocalDateTime dueDate,
                LocalDateTime createdAt) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.dueDate = dueDate;
        this.createdAt = createdAt;
    }
}
